/** biome-ignore-all lint/suspicious/noExplicitAny: . */

type Nullable<T> = T | null;

type Point = [number, number, number];

type Rect = [Point, Point];

type BlockName = string;

type WorldBlockChangedInfo = Record<string, unknown>;

type GenericFunction = (...args: any[]) => any;

declare const api: {
	ownerDbId: string;
	getPosition: GenericFunction;
	setPosition: GenericFunction;
	getPlayerIds: GenericFunction;
	playerIsInGame: GenericFunction;
	playerIsLoggedIn: GenericFunction;
	getPlayerPartyWhenJoined: GenericFunction;
	getNumPlayers: GenericFunction;
	getBlockCoordinatesPlayerStandingOn: GenericFunction;
	getBlockTypesPlayerStandingOn: GenericFunction;
	getUnitCoordinatesLifeformWithin: GenericFunction;
	showShopTutorial: GenericFunction;
	getShieldAmount: GenericFunction;
	setShieldAmount: GenericFunction;
	getHealth: GenericFunction;
	applyHealthChange: GenericFunction;
	setHealth: GenericFunction;
	applyMeleeHit: GenericFunction;
	attemptApplyDamage: GenericFunction;
	forceRespawn: GenericFunction;
	killLifeform: GenericFunction;
	getCurrentKillstreak: GenericFunction;
	clearKillstreak: GenericFunction;
	isAlive: GenericFunction;
	broadcastMessage: GenericFunction;
	sendMessage: GenericFunction;
	sendFlyingMiddleMessage: GenericFunction;
	setClientOption: GenericFunction;
	getClientOption: GenericFunction;
	createShopItem: GenericFunction;
	updateShopItem: GenericFunction;
	deleteShopItem: GenericFunction;
	configureShopCategory: GenericFunction;
	createShopItemForPlayer: GenericFunction;
	updateShopItemForPlayer: GenericFunction;
	resetShopItemForPlayer: GenericFunction;
	configureShopCategoryForPlayer: GenericFunction;
	setClientOptions: GenericFunction;
	setClientOptionToDefault: GenericFunction;
	setTargetedPlayerSettingForEveryone: GenericFunction;
	setEveryoneSettingForPlayer: GenericFunction;
	setOtherEntitySetting: GenericFunction;
	setOtherEntitySettings: GenericFunction;
	getOtherEntitySetting: GenericFunction;
	playParticleEffect: GenericFunction;
	getEntityName: GenericFunction;
	getPlayerId: GenericFunction;
	getPlayerDbId: GenericFunction;
	getPlayerIdFromDbId: GenericFunction;
	kickPlayer: GenericFunction;
	isBlockInLoadedChunk: GenericFunction;
	getBlock: GenericFunction;
	getBlockId: GenericFunction;
	setBlock: GenericFunction;
	attemptWorldChangeBlock: GenericFunction;
	getBlockSolidity: GenericFunction;
	setBlockRect: GenericFunction;
	setBlockWalls: GenericFunction;
	getChunk: GenericFunction;
	getEmptyChunk: GenericFunction;
	getMetaInfo: GenericFunction;
	blockNameToBlockId: GenericFunction;
	blockIdToBlockName: GenericFunction;
	blockCoordToChunkId: GenericFunction;
	chunkIdToBotLeftCoord: GenericFunction;
	sendTopRightHelper: GenericFunction;
	isMobile: GenericFunction;
	createItemDrop: GenericFunction;
	setCantPickUpItem: GenericFunction;
	deleteItemDrop: GenericFunction;
	getInitialItemMetadata: GenericFunction;
	getItemStat: GenericFunction;
	setCameraDirection: GenericFunction;
	setPlayerOpacity: GenericFunction;
	setPlayerOpacityForOnePlayer: GenericFunction;
	now: GenericFunction;
	checkValid: GenericFunction;
	setCanChangeBlock: GenericFunction;
	setCantChangeBlock: GenericFunction;
	setCanChangeBlockType: GenericFunction;
	setCantChangeBlockType: GenericFunction;
	resetCanChangeBlockType: GenericFunction;
	setCanChangeBlockRect: GenericFunction;
	setCantChangeBlockRect: GenericFunction;
	resetCanChangeBlockRect: GenericFunction;
	setWalkThroughType: GenericFunction;
	setWalkThroughRect: GenericFunction;
	giveItem: GenericFunction;
	inventoryIsFull: GenericFunction;
	setItemSlot: GenericFunction;
	removeItemName: GenericFunction;
	getItemSlot: GenericFunction;
	hasItem: GenericFunction;
	getInventoryItemAmount: GenericFunction;
	clearInventory: GenericFunction;
	setSelectedInventorySlotI: GenericFunction;
	getSelectedInventorySlotI: GenericFunction;
	getHeldItem: GenericFunction;
	getInventoryFreeSlotCount: GenericFunction;
	canOpenStandardChest: GenericFunction;
	giveStandardChestItem: GenericFunction;
	getStandardChestFreeSlotCount: GenericFunction;
	getStandardChestItemAmount: GenericFunction;
	getStandardChestItemSlot: GenericFunction;
	getStandardChestItems: GenericFunction;
	setStandardChestItemSlot: GenericFunction;
	getMoonstoneChestItemSlot: GenericFunction;
	getMoonstoneChestItems: GenericFunction;
	setMoonstoneChestItemSlot: GenericFunction;
	setBlockData: GenericFunction;
	getBlockData: GenericFunction;
	getLobbyName: GenericFunction;
	isPublicLobby: GenericFunction;
	getLobbyType: GenericFunction;
	progressBarUpdate: GenericFunction;
	initiateMiddleScreenBar: GenericFunction;
	removeMiddleScreenBar: GenericFunction;
	sendHitmarker: GenericFunction;
	setDirectionArrow: GenericFunction;
	clearDirectionArrow: GenericFunction;
	editItemCraftingRecipes: GenericFunction;
	resetItemCraftingRecipes: GenericFunction;
	removeItemCraftingRecipes: GenericFunction;
	isInsideRect: GenericFunction;
	getEntitiesInRect: GenericFunction;
	getEntityType: GenericFunction;
	createMobHerd: GenericFunction;
	attemptSpawnMob: GenericFunction;
	despawnMob: GenericFunction;
	getDefaultMobSetting: GenericFunction;
	setDefaultMobSetting: GenericFunction;
	getMobSetting: GenericFunction;
	setMobSetting: GenericFunction;
	getNumMobs: GenericFunction;
	getMobIds: GenericFunction;
	getMobAiState: GenericFunction;
	setMobAiState: GenericFunction;
	applyImpulse: GenericFunction;
	getVelocity: GenericFunction;
	setVelocity: GenericFunction;
	setEntityHeading: GenericFunction;
	getEntityHeading: GenericFunction;
	setItemAmount: GenericFunction;
	setMaxPlayers: GenericFunction;
	addQTE: GenericFunction;
	deleteQTE: GenericFunction;
	hasActiveQTE: GenericFunction;
	sendOverShopInfo: GenericFunction;
	openShop: GenericFunction;
	applyEffect: GenericFunction;
	getEffects: GenericFunction;
	removeEffect: GenericFunction;
	changePlayerIntoSkin: GenericFunction;
	removeAppliedSkin: GenericFunction;
	getPlayerCosmetic: GenericFunction;
	scalePlayerMeshNodes: GenericFunction;
	updateEntityNodeMeshAttachment: GenericFunction;
	setPlayerPose: GenericFunction;
	setPlayerPhysicsState: GenericFunction;
	getPlayerPhysicsState: GenericFunction;
	addFollowingEntityToPlayer: GenericFunction;
	removeFollowingEntityFromPlayer: GenericFunction;
	setCameraZoom: GenericFunction;
	playSound: GenericFunction;
	broadcastSound: GenericFunction;
	playClientPredictedSound: GenericFunction;
	calcExplosionForce: GenericFunction;
	getPlayerTargetInfo: GenericFunction;
	getPlayerFacingInfo: GenericFunction;
	raycastForBlock: GenericFunction;
	isPlayerCrouching: GenericFunction;
	getAuraInfo: GenericFunction;
	setTotalAura: GenericFunction;
	setAuraLevel: GenericFunction;
	applyAuraChange: GenericFunction;
	setCallbackValueFallback: GenericFunction;
	[key: string]: never;
}

declare let tick: GenericFunction;
declare let onClose: GenericFunction;
declare let onPlayerJoin: GenericFunction;
declare let onPlayerLeave: GenericFunction;
declare let onPlayerJump: GenericFunction;
declare let onRespawnRequest: GenericFunction;
declare let playerCommand: GenericFunction;
declare let onPlayerChat: GenericFunction;
declare let onPlayerChangeBlock: GenericFunction;
declare let onPlayerDropItem: GenericFunction;
declare let onPlayerPickedUpItem: GenericFunction;
declare let onPlayerSelectInventorySlot: GenericFunction;
declare let onBlockStand: GenericFunction;
declare let onPlayerAttemptCraft: GenericFunction;
declare let onPlayerCraft: GenericFunction;
declare let onPlayerAttemptOpenChest: GenericFunction;
declare let onPlayerOpenedChest: GenericFunction;
declare let onPlayerMoveItemOutOfInventory: GenericFunction;
declare let onPlayerMoveInvenItem: GenericFunction;
declare let onPlayerMoveItemIntoIdxs: GenericFunction;
declare let onPlayerSwapInvenSlots: GenericFunction;
declare let onPlayerMoveInvenItemWithAmt: GenericFunction;
declare let onPlayerAttemptAltAction: GenericFunction;
declare let onPlayerAltAction: GenericFunction;
declare let onPlayerClick: GenericFunction;
declare let onClientOptionUpdated: GenericFunction;
declare let onMobSettingUpdated: GenericFunction;
declare let onInventoryUpdated: GenericFunction;
declare let onChestUpdated: GenericFunction;
declare let onWorldChangeBlock: GenericFunction;
declare let onCreateBloxdMeshEntity: GenericFunction;
declare let onEntityCollision: GenericFunction;
declare let onPlayerAttemptSpawnMob: GenericFunction;
declare let onWorldAttemptSpawnMob: GenericFunction;
declare let onPlayerSpawnMob: GenericFunction;
declare let onWorldSpawnMob: GenericFunction;
declare let onWorldAttemptDespawnMob: GenericFunction;
declare let onMobDespawned: GenericFunction;
declare let onPlayerAttack: GenericFunction;
declare let onPlayerDamagingOtherPlayer: GenericFunction;
declare let onPlayerDamagingMob: GenericFunction;
declare let onMobDamagingPlayer: GenericFunction;
declare let onMobDamagingOtherMob: GenericFunction;
declare let onAttemptKillPlayer: GenericFunction;
declare let onPlayerKilledOtherPlayer: GenericFunction;
declare let onMobKilledPlayer: GenericFunction;
declare let onPlayerKilledMob: GenericFunction;
declare let onMobKilledOtherMob: GenericFunction;
declare let onPlayerPotionEffect: GenericFunction;
declare let onPlayerDamagingMeshEntity: GenericFunction;
declare let onPlayerBreakMeshEntity: GenericFunction;
declare let onPlayerUsedThrowable: GenericFunction;
declare let onPlayerThrowableHitTerrain: GenericFunction;
declare let onTouchscreenActionButton: GenericFunction;
declare let onTaskClaimed: GenericFunction;
declare let onChunkLoaded: GenericFunction;
declare let onPlayerRequestChunk: GenericFunction;
declare let onItemDropCreated: GenericFunction;
declare let onPlayerStartChargingItem: GenericFunction;
declare let onPlayerFinishChargingItem: GenericFunction;
declare let onPlayerFinishQTE: GenericFunction;
declare let onPlayerBoughtShopItem: GenericFunction;
declare let doPeriodicSave: GenericFunction;